spring.application.name=billtracker

# Server
server.port=${PORT:8080}

server.forward-headers-strategy=native

# MongoDB Atlas
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/billtracker}
spring.data.mongodb.auto-index-creation=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Gemini
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

cors.allowed-origins=http://localhost:5173, https://settle-up-boys.web.app, https://settle-up-boys.firebaseapp.com

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Google OAuth
google.client-id={GOOGLE_CLIENT_ID}
