spring.application.name=billtracker

# Server
server.port=${PORT:8080}

server.forward-headers-strategy=native

# PostgreSQL
spring.cloud.gcp.sql.database-name=${DB_NAME}
spring.cloud.gcp.sql.instance-connection-name=${DB_CONNECTION_NAME}

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.cloud.gcp.sql.enabled=${CLOUD_SQL_ENABLED}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Gemini
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent

# CORS
cors.allowed-origins=https://can-you-settle-the-bill.web.app, https://can-you-settle-the-bill.firebaseapp.com/

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
